In [3]:
import numpy as np

In [10]:
tinggi = [57,89,67,18]
lebar = [45,77,17]

In [7]:
arr_tinggi = np.array(tinggi)
arr_lebar = np.array(lebar)

hasil = arr_tinggi * arr_lebar

In [11]:
print(hasil, type(hasil))

[2565 6853 1139 1620] <class 'numpy.ndarray'>


#array 2D = ada array didalam array
[
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]
]

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.empty(4)

array([2.12199579e-314, 2.16847386e-028, 2.68771711e-321, 3.79442416e-321])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr_numbers = np.arange(7, 15, 2)
arr_numbers

array([ 7,  9, 11, 13])

In [30]:
arr_numbers = np.append(arr_numbers, 15)
arr_numbers

array([ 7,  9, 11, 13, 15])

In [34]:
hasil = np.append(arr_numbers, [15, 17])
hasil


array([ 7,  9, 11, 13, 15, 15, 17])

In [35]:
hasil_return = np.delete(hasil,1)
print(hasil_return)

[ 7 11 13 15 15 17]


In [36]:
random_num = np.array([-1,2,9,-5])
np.sort(random_num)

array([-5, -1,  2,  9])

#numpy tidak kena pass by refrence

In [38]:
.ndim 
.size
.shape
#bukan function, tidak perlu di () invoke

1

In [45]:
random_num.shape

(4,)

In [49]:
arr_2d = np.array([
    ["o","x","o"],
    ["x","x","o"]
])

In [42]:
arr_2d.ndim

2

In [43]:
arr_2d.size

9

In [50]:
arr_2d.shape

(2, 3)

In [52]:
transposes = arr_2d.reshape(3,2)
print(transposes)

[['o' 'x']
 ['o' 'x']
 ['x' 'o']]


In [60]:
print(random_num)

arr_nums_baru = random_num[np.newaxis] #menambahkan dimensi/axis baru
print(arr_nums_baru) 

[-1  2  9 -5]
[[-1  2  9 -5]]


In [61]:
random_num[:, np.newaxis]

array([[-1],
       [ 2],
       [ 9],
       [-5]])

In [62]:
np.expand_dims(random_num, axis=0)

array([[-1,  2,  9, -5]])

In [63]:
np.expand_dims(random_num, axis=1)

array([[-1],
       [ 2],
       [ 9],
       [-5]])

In [64]:
random_num[-3:]

array([ 2,  9, -5])

cara indexing dan slicing di numpy array sama persis dengan list biasa

In [68]:
random_num[random_num < 0]

array([-1, -5])

In [73]:
arr_a = np.array([[1,2], [3,4], [-1,-2]])
arr_a

array([[ 1,  2],
       [ 3,  4],
       [-1, -2]])

In [76]:
arr_b = np.array([[5,6], [7,8], [9,10]])
arr_b

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [74]:
np.vstack((arr_a, arr_b))

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [ 5,  6],
       [ 7,  8]])

In [79]:
iya = np.hstack((arr_a, arr_b))
print(iya)

[[ 1  2  5  6]
 [ 3  4  7  8]
 [-1 -2  9 10]]


In [82]:
iya_2 = np.hsplit(iya, 2)
type(iya_2)

list

In [87]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [90]:
b = a.view()
print(b)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [92]:
print(np.ones(8))

[1. 1. 1. 1. 1. 1. 1. 1.]


In [100]:
print(a)

print(a.reshape(3,4)+np.ones(12).reshape(3,4)) #pertambahan vektor harus sama isi nya

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [102]:
a*9

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [103]:
a/7

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857])

In [117]:
m1 = np.array([
    [2,6,5],
    [139, 154, 75]
    
])

m2 = np.array([
    [9,5],
    [78,45],
    [35,89]
])

hasil = np.dot(m1,m2)
print(hasil)

[[  661   725]
 [15888 14300]]


In [119]:
m2[0,0]

9

In [122]:
m2[:,1]

array([ 5, 45, 89])

In [126]:
np.zeros((4,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])